"""Генерация build_model.py из Blueprint."""

from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_SERVICES = _ROOT / "services"
if str(_SERVICES) not in sys.path:
    sys.path.insert(0, str(_SERVICES))

from worker.core.python_exporter import (  # noqa: E402
    _sanitize_var_name,
    generate_python_script,
)


class TestPythonExporter(unittest.TestCase):
    def test_sanitize(self) -> None:
        self.assertEqual(_sanitize_var_name("piston_head"), "piston_head")
        self.assertEqual(_sanitize_var_name("123x"), "part_123x")
        self.assertEqual(_sanitize_var_name("a-b"), "a_b")

    def test_generate_contains_build_assembly_and_main(self) -> None:
        path = _ROOT / "examples" / "piston-assembly.blueprint.json"
        payload = json.loads(path.read_text(encoding="utf-8"))
        src = generate_python_script(payload)
        self.assertIn("def build_assembly()", src)
        self.assertIn('if __name__ == "__main__":', src)
        self.assertIn("Auto-generated by AI-Forge", src)
        self.assertIn("piston_head", src)

    def test_generate_revolved_profile_emits_revolve(self) -> None:
        path = _ROOT / "examples" / "demo-revolve-pulley.json"
        payload = json.loads(path.read_text(encoding="utf-8"))
        src = generate_python_script(payload)
        self.assertIn('cq.Workplane("XZ")', src)
        self.assertIn(".revolve(", src)
        self.assertIn("pulley_wheel", src)

    def test_bearing_and_gear_preview_in_script(self) -> None:
        payload = {
            "geometry": {
                "parts": [
                    {
                        "part_id": "b1",
                        "base_shape": "bearing",
                        "parameters": {"series": "608zz"},
                        "operations": [],
                    },
                    {
                        "part_id": "g1",
                        "base_shape": "gear",
                        "parameters": {
                            "module": 2.0,
                            "teeth": 20,
                            "thickness": 10.0,
                            "bore_diameter": 8.0,
                            "high_lod": False,
                        },
                        "operations": [],
                    },
                ]
            }
        }
        src = generate_python_script(payload)
        self.assertIn("make_bearing_ring", src)
        self.assertIn("'608zz'", src)
        self.assertIn("make_gear_preview", src)
        self.assertIn("b1 = make_bearing_ring", src)
        self.assertIn("g1 = make_gear_preview", src)

    def test_gear_high_lod_not_added(self) -> None:
        payload = {
            "geometry": {
                "parts": [
                    {
                        "part_id": "g_hi",
                        "base_shape": "gear",
                        "parameters": {
                            "module": 2.0,
                            "teeth": 20,
                            "thickness": 10.0,
                            "bore_diameter": 8.0,
                            "high_lod": True,
                        },
                        "operations": [],
                    }
                ]
            }
        }
        src = generate_python_script(payload)
        self.assertIn("high_lod=true", src)
        self.assertIn("g_hi = None", src)
        self.assertIn("was not added", src)


if __name__ == "__main__":
    unittest.main()
